In [1]:
pip install google-play-scraper

Collecting google-play-scraper
  Downloading google_play_scraper-1.2.7-py3-none-any.whl.metadata (50 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.2/50.2 kB 2.6 MB/s eta 0:00:00
Downloading google_play_scraper-1.2.7-py3-none-any.whl (28 kB)
Installing collected packages: google-play-scraper
Successfully installed google-play-scraper-1.2.7

In [2]:
import pandas as pd
from google_play_scraper import Sort, reviews

# App ID e-wallet Indonesia from Play Store
apps = {
    'GoPay': 'com.gojek.app',
    'OVO': 'ovo.id',
    'DANA': 'id.dana'
}

all_reviews = []

In [3]:
# Extract user reviews for each application
for app_name, app_id in apps.items():
    print(f"Scraping review data for: {app_name}...")

    # Retrieve the 5000 most recent reviews per application
    result, _ = reviews(
        app_id,
        lang='id',
        country='id',
        sort=Sort.NEWEST,
        count=5000
    )

    # Append the application identifier to each review entry
    for item in result:
        item['app_name'] = app_name
        all_reviews.append(item)

Scraping review data for: GoPay...
Scraping review data for: OVO...
Scraping review data for: DANA...

In [4]:
# Convert the extracted raw data into a Pandas DataFrame
df = pd.DataFrame(all_reviews)

In [5]:
df

,reviewId,userName,userImage,content,score,thumbsUpCount,reviewCreatedVersion,at,replyContent,repliedAt,appVersion,app_name
0,55ac731e-d9a9-4a74-bdb8-035d0887b267,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,Mau cepat atau paket hemat selalu tersedia arm...,5,0,5.74.1,2026-08-30 09:17:40,None,NaT,5.74.1,GoPay
1,ffb3d935-ef19-46c4-b396-526854cf094c,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,"Tolong.. potongan untuk driver nya, jangan bes...",5,0,5.73.2,2026-08-30 09:12:32,None,NaT,5.73.2,GoPay
2,1895f40b-9c34-408d-aaca-92ef44ed4124,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,gofood lamaaa,3,0,5.74.1,2026-08-30 08:40:16,"Hai Kak Jihan, mohon maaf keterlambatan pengir...",2026-08-30 09:06:52,5.74.1,GoPay
3,4e30e588-ad4e-4832-83c5-7a4b45970f05,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,kalo gada driver yg mau ngambil tu coba gausah...,1,0,None,2026-08-30 08:34:03,Mohon maaf atas kendalanya Kak Azalea. Kesulit...,2026-08-30 09:05:30,None,GoPay
4,b18e9644-15d5-4d08-ade0-8a66dc84a954,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,so comfortable,5,0,5.74.1,2026-08-30 08:21:26,None,NaT,5.74.1,GoPay
...,...,...,...,...,...,...,...,...,...,...,...,...
14995,ca7ec2ee-c592-42ea-80bf-6fdad8d9550c,Dani Prayoga,https://play-lh.googleusercontent.com/a/ACg8oc...,sangat membantu,5,0,2.139.2,2026-08-24 05:15:41,None,NaT,2.139.2,DANA
14996,42a692d0-aa1d-485e-a4b1-0a44a92d083c,Aidilbahsyarbbasir2008 Aidil,https://play-lh.googleusercontent.com/a/ACg8oc...,uang habis di tarik gogle ngga tau di tarik kr...,1,0,2.139.2,2026-08-24 05:12:44,"Hi Kak, kami paham kekhawatiranmu transaksi Go...",2026-08-24 06:22:43,2.139.2,DANA
14997,fdbcb8a0-6668-42a3-98b0-3b1ecbcc0d49,arkanzapermana permana,https://play-lh.googleusercontent.com/a/ACg8oc...,bagus,5,0,2.139.2,2026-08-24 05:11:41,None,NaT,2.139.2,DANA
14998,6e12da8d-b292-4834-9bb4-067b8cb75b99,alvin,https://play-lh.googleusercontent.com/a/ACg8oc...,pakai dana lebih mudah,5,0,None,2026-08-24 05:09:53,None,NaT,None,DANA
14999,58ecf4e0-7e94-4c08-a697-368fc934f8e3,Iyas Spdn,https://play-lh.googleusercontent.com/a-/ALV-U...,mantap cepat akurat,5,0,None,2026-08-24 05:07:28,None,NaT,None,DANA

In [6]:
# Filter and retain only the relevant attributes
cols_to_keep = ['app_name', 'userName', 'score', 'at', 'content', 'appVersion']
df_clean = df[cols_to_keep]

# Display data summary and preview
print("\nExtraction completed successfully! Preview of the dataset:")
display(df_clean.head())
print(f"\nTotal collected reviews: {len(df_clean)} rows")

Extraction completed successfully! Preview of the dataset:

,app_name,userName,score,at,content,appVersion
0,GoPay,Pengguna Google,5,2026-08-30 09:17:40,Mau cepat atau paket hemat selalu tersedia arm...,5.74.1
1,GoPay,Pengguna Google,5,2026-08-30 09:12:32,"Tolong.. potongan untuk driver nya, jangan bes...",5.73.2
2,GoPay,Pengguna Google,3,2026-08-30 08:40:16,gofood lamaaa,5.74.1
3,GoPay,Pengguna Google,1,2026-08-30 08:34:03,kalo gada driver yg mau ngambil tu coba gausah...,None
4,GoPay,Pengguna Google,5,2026-08-30 08:21:26,so comfortable,5.74.1

Total collected reviews: 15000 rows

In [7]:
# Export & Download CSV
df_clean.to_csv('ewallet_reviews.csv', index=False)

from google.colab import files
files.download('ewallet_reviews.csv')